name: create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OUTPUT_PATH: 'launcher/build/outputs/apk/release'
      MAPPINGS_OUTPUT_PATH: 'launcher/build/outputs/mapping/release'

    steps:
      - uses: actions/checkout@v4.1.1

      - name: set up jdk
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 1.17
          distribution: zulu

      - name: decode keystore
        uses: italankin/android-keystore-decode-action@v1
        with:
          output_dir: 'launcher/'
          keystore_name: 'release.keystore'
          properties_name: 'release.properties'
          encoded_keystore: ${{ secrets.KEYSTORE_BASE64 }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          key_alias_password: ${{ secrets.KEYSTORE_KEY_ALIAS_PASSWORD }}

      - name: make gradlew executable
        run: chmod +x gradlew

      - name: assemble
        run: ./gradlew --no-daemon assembleRelease

      - name: current tag
        id: current_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: rename apk
        run: mv "$OUTPUT_PATH/launcher-release.apk" "$OUTPUT_PATH/lnch-${{ steps.current_tag.outputs.tag }}.apk"

      - name: release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "${{ env.OUTPUT_PATH }}/*.apk"
          prerelease: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: save mapping.txt
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mapping.txt
          path: ${{ env.MAPPINGS_OUTPUT_PATH }}/mapping.txt

