name: create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APK_OUTPUT_PATH: 'launcher/build/outputs/apk/release'
      AAB_OUTPUT_PATH: 'launcher/build/outputs/bundle/release'

    steps:
      - uses: actions/checkout@v4.1.1

      - name: set up jdk
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: decode keystore
        uses: italankin/android-keystore-decode-action@v1
        with:
          output_dir: 'launcher/'
          keystore_name: 'release.keystore'
          properties_name: 'release.properties'
          encoded_keystore: ${{ secrets.KEYSTORE_BASE64 }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          key_alias_password: ${{ secrets.KEYSTORE_KEY_ALIAS_PASSWORD }}

      - name: make gradlew executable
        run: chmod +x gradlew

      - name: assemble
        run: ./gradlew --no-daemon assembleRelease bundleRelease

      - name: current ref
        run: echo "CURRENT_REF=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: rename apk
        run: mv "$APK_OUTPUT_PATH/launcher-release.apk" "$APK_OUTPUT_PATH/lnch-${{ env.CURRENT_REF }}.apk"

      - name: release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "${{ env.APK_OUTPUT_PATH }}/*.apk"
          prerelease: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload bundle
        uses: italankin/google-play-aab-uploader@1.3
        with:
          package-name: 'com.italankin.lnch'
          aab-path: "${{ env.AAB_OUTPUT_PATH }}/launcher-release.aab"
          key-json: ${{ secrets.SERVICE_KEY_JSON }}
